### ISSUE TITLE
Postgresql 12 support notes

### ISSUE THREAD

**Issue by speedo-spin** [SchemaPlus/schema_plus_triggers#1]
For postgres v12 `create_trigger` produces `EXECUTE FUNCTION` instead of `EXECUTE PROCEDURE` in schema.rb:
```rb
create_trigger :table, :trigger, "AFTER INSERT OR DELETE OR UPDATE", <<-'END_TRIGGER_...', :force => true
FOR EACH ROW EXECUTE FUNCTION ...
```

For postgres v9 it produces `EXECUTE PROCEDURE`, as expected

**Comment by urkle** [comment]
So this isn't an issue at all.  As technically that is executing a "function".  From the PG 12 documentation on the create trigger statement  ( [docs](https://www.postgresql.org/docs/12/sql-createtrigger.html) )

```
In the syntax of CREATE TRIGGER, the keywords FUNCTION and PROCEDURE are equivalent, but the referenced function must in any case be a function, not a procedure. The use of the keyword PROCEDURE here is historical and deprecated.
```

Thus when upgrading to PG 12 the schema.rb will be slightly changed but has the same meaning. Further that "for each row execute ..." is provided by PostgreSQL as the official definition of the trigger.
